version: 0.0
os: linux
files:
  - source: /app.js
    destination: /usr/share/nginx/html
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
